#!/usr/bin/env bash
# Bootstrap Neon PostgreSQL for PlanFlow (beginner-friendly).
#
# What this script does:
# 1) Checks NEON_API_KEY
# 2) Lists existing Neon projects; reuses one named "planflow" if present
# 3) Otherwise creates a new project named "planflow"
# 4) Prints / writes DATABASE_URL for FastAPI
#
# Usage:
#   export NEON_API_KEY=...
#   ./scripts/neon_bootstrap.sh
#
# Optional:
#   NEON_PROJECT_NAME=planflow ./scripts/neon_bootstrap.sh
#   NEON_REGION=aws-ap-southeast-1 ./scripts/neon_bootstrap.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PROJECT_NAME="${NEON_PROJECT_NAME:-planflow}"
REGION_ID="${NEON_REGION:-aws-ap-southeast-1}"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
OUTPUT_JSON="${OUTPUT_JSON:-$ROOT_DIR/.neon-bootstrap.json}"

if [[ -z "${NEON_API_KEY:-}" ]]; then
  echo "ERROR: NEON_API_KEY is not set."
  echo "Create an API key in Neon Console → Account settings → API keys,"
  echo "then: export NEON_API_KEY=your_key"
  exit 1
fi

if ! command -v neonctl >/dev/null 2>&1 && ! command -v neon >/dev/null 2>&1; then
  echo "Installing neonctl into ~/.npm-global ..."
  mkdir -p "$HOME/.npm-global"
  npm config set prefix "$HOME/.npm-global"
  export PATH="$HOME/.npm-global/bin:$PATH"
  npm i -g neonctl@latest
fi

export PATH="${HOME}/.npm-global/bin:${PATH}"
NEON_BIN="$(command -v neonctl || command -v neon)"

echo "==> Using CLI: $NEON_BIN"

ORG_ARGS=()
if [[ -n "${NEON_ORG_ID:-}" ]]; then
  ORG_ARGS=(--org-id "$NEON_ORG_ID")
  echo "==> Using org from NEON_ORG_ID: $NEON_ORG_ID"
else
  echo "==> Listing Neon organizations ..."
  ORGS_JSON="$("$NEON_BIN" orgs list --output json --api-key "$NEON_API_KEY" || true)"
  DETECTED_ORG="$(
    python3 - <<'PY' "${ORGS_JSON:-[]}"
import json, sys
raw = sys.argv[1] if len(sys.argv) > 1 else "[]"
try:
    data = json.loads(raw or "[]")
except json.JSONDecodeError:
    data = []
orgs = data.get("organizations", data) if isinstance(data, dict) else data
if isinstance(orgs, list) and len(orgs) == 1 and orgs[0].get("id"):
    print(orgs[0]["id"])
else:
    print("")
PY
  )"
  if [[ -n "$DETECTED_ORG" ]]; then
    ORG_ARGS=(--org-id "$DETECTED_ORG")
    echo "==> Auto-selected sole org: $DETECTED_ORG"
  fi
fi

echo "==> Listing Neon projects ..."
PROJECTS_JSON="$("$NEON_BIN" projects list --output json --api-key "$NEON_API_KEY" "${ORG_ARGS[@]}")"

PROJECT_ID="$(
  python3 - <<'PY' "$PROJECTS_JSON" "$PROJECT_NAME"
import json, sys
projects = json.loads(sys.argv[1])
# CLI may return a list or {"projects": [...]}
if isinstance(projects, dict):
    projects = projects.get("projects", [])
name = sys.argv[2]
match = next((p for p in projects if p.get("name") == name), None)
print(match["id"] if match else "")
PY
)"

if [[ -n "$PROJECT_ID" ]]; then
  echo "==> Reusing existing project '$PROJECT_NAME' ($PROJECT_ID)"
else
  echo "==> Creating Neon project '$PROJECT_NAME' in $REGION_ID ..."
  CREATE_JSON="$("$NEON_BIN" projects create \
    --name "$PROJECT_NAME" \
    --region-id "$REGION_ID" \
    --database neondb \
    --output json \
    --api-key "$NEON_API_KEY" \
    "${ORG_ARGS[@]}")"
  echo "$CREATE_JSON" > "$OUTPUT_JSON"
  PROJECT_ID="$(
    python3 - <<'PY' "$CREATE_JSON"
import json, sys
data = json.loads(sys.argv[1])
project = data.get("project", data)
print(project["id"])
PY
  )"
  echo "==> Created project id: $PROJECT_ID"
fi

echo "==> Fetching pooled connection string ..."
DATABASE_URL="$("$NEON_BIN" connection-string \
  --project-id "$PROJECT_ID" \
  --pooled \
  --api-key "$NEON_API_KEY")"
# Persist for local uvicorn without exporting secrets into git
umask 077
{
  echo "# Generated by scripts/neon_bootstrap.sh — do not commit"
  echo "DATABASE_URL=$DATABASE_URL"
} > "$ENV_FILE"

# Also write a redacted helper file for humans
python3 - <<'PY' "$DATABASE_URL" "$PROJECT_ID" "$PROJECT_NAME" "$OUTPUT_JSON"
import json, sys
from urllib.parse import urlparse

url, project_id, name, out = sys.argv[1:5]
parsed = urlparse(url)
redacted = parsed._replace(netloc=f"{parsed.username}:***@{parsed.hostname}" + (f":{parsed.port}" if parsed.port else "")).geturl()
payload = {
    "project_name": name,
    "project_id": project_id,
    "database_url_redacted": redacted,
    "host": parsed.hostname,
}
with open(out, "w", encoding="utf-8") as f:
    json.dump(payload, f, indent=2)
    f.write("\n")
print("Wrote", out)
print("Host:", parsed.hostname)
print("DATABASE_URL (password hidden):", redacted)
PY

echo
echo "Done."
echo "1) DATABASE_URL saved to: $ENV_FILE"
echo "2) Start API:"
echo "     cd backend && python3 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo "3) Test:"
echo "     curl -s http://127.0.0.1:8000/db/ping"
echo "     curl -s -X POST http://127.0.0.1:8000/db/smoke-test"
